### Begin DialogBlocks generated body
################################################################################
# Makefile generated by DialogBlocks
#
# Available configurations:
# debug
# release
################################################################################

CONFIG=debug

# debug
ifeq ($(CONFIG),debug)
WXWIN=/opt/wxGTK-2.8.10
TOOLCHAINNAME=gtk2ud
WXVERSION:=$(shell echo `$(WXWIN)/GCCBuildDebugGTK2Unicode/wx-config --version`)
CXX=g++
LINKER=g++
CC=gcc
RESCOMP=windres.exe
RCFILEOBJ=spriteKodo_rc.o
RCFILESRC=spriteKodo.rc
RESOURCEOBJECT=
OUTPUTPATH=GCCDebug
OBJECTPATH=GCCDebug
BUILDPATHS=$(OBJECTPATH)
PROGRAM=spriteKodo
LIBS=$(shell $(WXWIN)/GCCBuildDebugGTK2Unicode/wx-config --inplace --exec-prefix="$(WXWIN)/GCCBuildDebugGTK2Unicode" --libs std --cxxflags)
LINKERFLAGS=
WARNINGFLAGS=-Wall -Wno-write-strings
OPTFLAGS=-O0
DEBUGFLAGS=-ggdb
LIBPATH=
CPPINC:=$(shell $(WXWIN)/GCCBuildDebugGTK2Unicode/wx-config --inplace --cxxflags)
GCCFLAGS=
LDFLAGS=$(LIBS) $(LIBPATH) $(LINKERFLAGS)
CPPFLAGS=$(CPPINC) $(GCCFLAGS) $(DEBUGFLAGS) $(OPTFLAGS) $(WARNINGFLAGS)
LIBDIRNAME=$(WXWIN)/GCCBuildDebugGTK2Unicode/lib
RESPATH=--include-dir "$(WXWIN)/include" --include-dir "$(WXWIN)/contrib/include" --include-dir "$(WXWIN)/GCCBuildDebugGTK2Unicode/lib/wx/include/gtk2-unicode-debug-static-2.8"
MACPACKAGEINFO=

# release
else
WXWIN=/opt/wxGTK-2.8.10
TOOLCHAINNAME=gtk2u
WXVERSION:=$(shell echo `wx-config --version`)
CXX=g++
LINKER=g++
CC=gcc
RESCOMP=windres.exe
RCFILEOBJ=spriteKodo_rc.o
RCFILESRC=spriteKodo.rc
RESOURCEOBJECT=
OUTPUTPATH=GCCRelease
OBJECTPATH=GCCRelease
BUILDPATHS=$(OBJECTPATH)
PROGRAM=spriteKodo
LIBS=$(shell wx-config --libs std --cxxflags)
LINKERFLAGS=
WARNINGFLAGS=-Wall -Wno-write-strings
OPTFLAGS=-O2
DEBUGFLAGS=
LIBPATH=
CPPINC:=$(shell wx-config --cxxflags)
GCCFLAGS=
LDFLAGS=$(LIBS) $(LIBPATH) $(LINKERFLAGS)
CPPFLAGS=$(CPPINC) $(GCCFLAGS) $(DEBUGFLAGS) $(OPTFLAGS) $(WARNINGFLAGS)
LIBDIRNAME=$(WXWIN)/GCCBuildReleaseGTK2Unicode/lib
RESPATH=--include-dir "$(WXWIN)/include" --include-dir "$(WXWIN)/contrib/include" --include-dir "$(WXWIN)/GCCBuildReleaseGTK2Unicode/lib/wx/include/gtk2-unicode-release-static-2.8"
MACPACKAGEINFO=
endif

OBJECTS=$(OBJECTPATH)/CKodoUtil.o $(OBJECTPATH)/CSourceImage.o $(OBJECTPATH)/Packing.o $(OBJECTPATH)/spritekodoapp.o $(OBJECTPATH)/spritekodomainwnd.o $(RESOURCEOBJECT)

all:	$(BUILDPATHS) $(MACPACKAGEINFO) $(OUTPUTPATH)/$(PROGRAM)

$(OBJECTPATH):
	mkdir -p $(OBJECTPATH)

clean:
	rm -f $(OBJECTPATH)/*.o
	rm -f $(OBJECTPATH)/*.res
	rm -fr .deps .pch
	rm -fr $(PROGRAM).app
	rm -f $(OUTPUTPATH)/$(PROGRAM)

help:
	@echo "Usage: make -f Makefile CONFIG=[debug|release] [all|clean|help]"

$(OUTPUTPATH)/$(PROGRAM):	$(OBJECTS)
	$(LINKER) -o $@ $(OBJECTS) $(LDFLAGS)


# Windows only
$(OBJECTPATH)/$(RCFILEOBJ):	$(RCFILESRC)
	$(RESCOMP) --use-temp-file -i$< -o$@ $(RESPATH) --include-dir . --define NOPCH

# Mac only
$(OUTPUTPATH)/$(PROGRAM).app/Contents/PkgInfo: $(OUTPUTPATH)/$(PROGRAM) $(INFOPLISTSOURCE) $(ICNSSOURCE)
	mkdir -p $(OUTPUTPATH)/$(PROGRAM).app/Contents
	mkdir -p $(OUTPUTPATH)/$(PROGRAM).app/Contents/MacOS
	mkdir -p $(OUTPUTPATH)/$(PROGRAM).app/Contents/Resources
	sed -e "s/IDENTIFIER/$(PROGRAM)/" \
	-e "s/EXECUTABLE/$(PROGRAM)/" \
	-e "s/VERSION/$(WXVERSION)/" \
	$(INFOPLISTSOURCE) >$(OUTPUTPATH)/$(PROGRAM).app/Contents/Info.plist
	echo -n "APPL????" >$(OUTPUTPATH)/$(PROGRAM).app/Contents/PkgInfo
	ln -f $(OUTPUTPATH)/$(PROGRAM) $(OUTPUTPATH)/$(PROGRAM).app/Contents/MacOS/$(PROGRAM)
	cp -f $(ICNSSOURCE) $(ICNSDEST)

$(OBJECTPATH)/CKodoUtil.o:	CKodoUtil.cpp CKodoUtil.h CSourceImage.h Packing.h
	$(CXX) -c -o $@ $(CPPFLAGS) CKodoUtil.cpp

$(OBJECTPATH)/CSourceImage.o:	CSourceImage.cpp CSourceImage.h
	$(CXX) -c -o $@ $(CPPFLAGS) CSourceImage.cpp

$(OBJECTPATH)/Packing.o:	Packing.cpp Packing.h CSourceImage.h
	$(CXX) -c -o $@ $(CPPFLAGS) Packing.cpp

$(OBJECTPATH)/spritekodoapp.o:	spritekodoapp.cpp spritekodoapp.h spritekodomainwnd.h CSourceImage.h CKodoUtil.h
	$(CXX) -c -o $@ $(CPPFLAGS) spritekodoapp.cpp

$(OBJECTPATH)/spritekodomainwnd.o:	spritekodomainwnd.cpp spritekodomainwnd.h CSourceImage.h CKodoUtil.h
	$(CXX) -c -o $@ $(CPPFLAGS) spritekodomainwnd.cpp

.PHONY:	all clean
### End DialogBlocks generated body
